#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_FIREBALL 40

#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_PIPE 6
#define OBJECT_TYPE_BUSH 7
#define OBJECT_TYPE_RECT_PLATFORM 8
#define OBJECT_TYPE_BRICK_PLATFORM 9
#define OBJECT_TYPE_VENUS_FIRE 10
#define OBJECT_TYPE_FIREBALL 11

#define OBJECT_TYPE_PORTAL	50

#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

#define ID_SPRITE_PIPE_HEAD 60000
#define ID_SPRITE_PIPE_BODY 60001

#define ID_SPRITE_BUSH 70000

#pragma region RECT_PLATFORM
#define ID_SPRITE_PLATFORM_WHITE_TOP_LEFT 80000
#define ID_SPRITE_PLATFORM_WHITE_TOP_RIGHT 80001
#define ID_SPRITE_PLATFORM_WHITE_BOTTOM_LEFT 80002
#define ID_SPRITE_PLATFORM_WHITE_BOTTOM_RIGHT 80003
#define ID_SPRITE_PLATFORM_WHITE_TOP 80004
#define ID_SPRITE_PLATFORM_WHITE_BOTTOM 80005
#define ID_SPRITE_PLATFORM_WHITE_LEFT 80006
#define ID_SPRITE_PLATFORM_WHITE_RIGHT 80007
#define ID_SPRITE_PLATFORM_WHITE_MIDDLE 80008

#define ID_SPRITE_PLATFORM_GREEN_TOP_LEFT 81000
#define ID_SPRITE_PLATFORM_GREEN_TOP_RIGHT 81001
#define ID_SPRITE_PLATFORM_GREEN_BOTTOM_LEFT 81002
#define ID_SPRITE_PLATFORM_GREEN_BOTTOM_RIGHT 81003
#define ID_SPRITE_PLATFORM_GREEN_TOP 81004
#define ID_SPRITE_PLATFORM_GREEN_BOTTOM 81005
#define ID_SPRITE_PLATFORM_GREEN_LEFT 81006
#define ID_SPRITE_PLATFORM_GREEN_RIGHT 81007
#define ID_SPRITE_PLATFORM_GREEN_MIDDLE 81008

#define ID_SPRITE_PLATFORM_PINK_TOP_LEFT 82000
#define ID_SPRITE_PLATFORM_PINK_TOP_RIGHT 82001
#define ID_SPRITE_PLATFORM_PINK_BOTTOM_LEFT 82002
#define ID_SPRITE_PLATFORM_PINK_BOTTOM_RIGHT 82003
#define ID_SPRITE_PLATFORM_PINK_TOP 82004
#define ID_SPRITE_PLATFORM_PINK_BOTTOM 82005
#define ID_SPRITE_PLATFORM_PINK_LEFT 82006
#define ID_SPRITE_PLATFORM_PINK_RIGHT 82007
#define ID_SPRITE_PLATFORM_PINK_MIDDLE 82008

#define ID_SPRITE_PLATFORM_BLUE_TOP_LEFT 83000
#define ID_SPRITE_PLATFORM_BLUE_TOP_RIGHT 83001
#define ID_SPRITE_PLATFORM_BLUE_BOTTOM_LEFT 83002
#define ID_SPRITE_PLATFORM_BLUE_BOTTOM_RIGHT 83003
#define ID_SPRITE_PLATFORM_BLUE_TOP 83004
#define ID_SPRITE_PLATFORM_BLUE_BOTTOM 83005
#define ID_SPRITE_PLATFORM_BLUE_LEFT 83006
#define ID_SPRITE_PLATFORM_BLUE_RIGHT 83007
#define ID_SPRITE_PLATFORM_BLUE_MIDDLE 83008

#define ID_SPRITE_PLATFORM_SHADOW 84000

#pragma endregion

#define ID_SPRITE_BRICK_PLATFORM_BEGIN 90000
#define ID_SPRITE_BRICK_PLATFORM_MIDDLE 90001
#define ID_SPRITE_BRICK_PLATFORM_END 90002
#define ID_SPRITE_BRICK_PLATFORM_2_BEGIN 91000
#define ID_SPRITE_BRICK_PLATFORM_2_MIDDLE 91001
#define ID_SPRITE_BRICK_PLATFORM_2_END 91002

#define ID_SPRITE_VENUS_FIRE_RED_LEFT_DOWN 100000
#define ID_SPRITE_VENUS_FIRE_RED_LEFT_UP 100001
#define ID_SPRITE_VENUS_FIRE_RED_RIGHT_DOWN 100002
#define ID_SPRITE_VENUS_FIRE_RED_RIGHT_UP 100003
#define ID_SPRITE_VENUS_FIRE_GREEN_LEFT_DOWN 100004
#define ID_SPRITE_VENUS_FIRE_GREEN_LEFT_UP 100005
#define ID_SPRITE_VENUS_FIRE_GREEN_RIGHT_DOWN 100006
#define ID_SPRITE_VENUS_FIRE_GREEN_RIGHT_UP 100007

#define ID_SPRITE_FIREBALL_0 200000
#define ID_SPRITE_FIREBALL_1 200001
#define ID_SPRITE_FIREBALL_2 200002
#define ID_SPRITE_FIREBALL_3 200003

#define ID_ANI_FIREBALL 200000